server:
  servlet:
    contextPath: /api/v1

spring:
  application:
    name: factory 
  profiles:
    active: dev
    include:
      - db

application:
  security:
    jwt:
      secret-key: 462D4A614E645266556A586E3272357538782F413F4428472B4B625065536856
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days
    jasypt:
      secret-key: 4B6250655368566D597133743677397A244326462948404D635166546A576E5A

---
spring.config.activate.on-profile: unittest
server:
  port: 8080
---
spring.config.activate.on-profile: dev
server:
  port: 8090
---
spring.config.activate.on-profile: product
server:
  port: 8080